export const CURRENCIES = [
  {
    currencyCode: "USD",
    currencyName: "US Dollar",
    countries: [
      "United States",
      "American Samoa",
      "British Indian Ocean Territory",
      "Ecuador",
      "El Salvador",
      "Guam",
      "Haiti",
      "Marshall Islands",
      "Micronesia",
      "Northern Mariana Islands",
      "Palau",
      "Panama",
      "Puerto Rico",
      "Timor-Leste",
      "Turks and Caicos Islands",
      "U.S. Virgin Islands",
    ],
  },
  {
    currencyCode: "EUR",
    currencyName: "Euro",
    countries: [
      "Austria",
      "Belgium",
      "Cyprus",
      "Estonia",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Ireland",
      "Italy",
      "Latvia",
      "Lithuania",
      "Luxembourg",
      "Malta",
      "Netherlands",
      "Portugal",
      "Slovakia",
      "Slovenia",
      "Spain",
    ],
  },
  {
    currencyCode: "JPY",
    currencyName: "Japanese Yen",
    countries: ["Japan"],
  },
  {
    currencyCode: "GBP",
    currencyName: "Pound Sterling",
    countries: [
      "United Kingdom",
      "South Georgia and the South Sandwich Islands",
    ],
  },
  {
    currencyCode: "AUD",
    currencyName: "Australian Dollar",
    countries: [
      "Australia",
      "Christmas Island",
      "Cocos (Keeling) Islands",
      "Heard Island and McDonald Islands",
      "Kiribati",
      "Nauru",
      "Norfolk Island",
      "Tuvalu",
    ],
  },
  {
    currencyCode: "CAD",
    currencyName: "Canadian Dollar",
    countries: ["Canada"],
  },
  {
    currencyCode: "CHF",
    currencyName: "Swiss Franc",
    countries: ["Switzerland", "Liechtenstein"],
  },
  {
    currencyCode: "CNY",
    currencyName: "Chinese Yuan",
    countries: ["China"],
  },
  {
    currencyCode: "SEK",
    currencyName: "Swedish Krona",
    countries: ["Sweden"],
  },
  {
    currencyCode: "NZD",
    currencyName: "New Zealand Dollar",
    countries: ["New Zealand", "Cook Islands", "Niue", "Pitcairn", "Tokelau"],
  },
  {
    currencyCode: "KRW",
    currencyName: "South Korean Won",
    countries: ["South Korea"],
  },
  {
    currencyCode: "SGD",
    currencyName: "Singapore Dollar",
    countries: ["Singapore"],
  },
  {
    currencyCode: "HKD",
    currencyName: "Hong Kong Dollar",
    countries: ["Hong Kong"],
  },
  {
    currencyCode: "NOK",
    currencyName: "Norwegian Krone",
    countries: ["Norway", "Bouvet Island"],
  },
  {
    currencyCode: "MXN",
    currencyName: "Mexican Peso",
    countries: ["Mexico"],
  },
  {
    currencyCode: "INR",
    currencyName: "Indian Rupee",
    countries: ["India"],
  },
  {
    currencyCode: "RUB",
    currencyName: "Russian Ruble",
    countries: ["Russia"],
  },
  {
    currencyCode: "ZAR",
    currencyName: "South African Rand",
    countries: ["South Africa"],
  },
  {
    currencyCode: "TRY",
    currencyName: "Turkish Lira",
    countries: ["Turkey"],
  },
  {
    currencyCode: "BRL",
    currencyName: "Brazilian Real",
    countries: ["Brazil"],
  },
];

export const ALLCOUNTRIES = [
  { name: "Afghanistan", code: "AF" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "Andorra", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Antigua and Barbuda", code: "AG" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bahamas", code: "BS" },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY" },
  { name: "Belgium", code: "BE" },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bhutan", code: "BT" },
  { name: "Bolivia", code: "BO" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Botswana", code: "BW" },
  { name: "Brazil", code: "BR" },
  { name: "Brunei", code: "BN" },
  { name: "Bulgaria", code: "BG" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Cabo Verde", code: "CV" },
  { name: "Cambodia", code: "KH" },
  { name: "Cameroon", code: "CM" },
  { name: "Canada", code: "CA" },
  { name: "Central African Republic", code: "CF" },
  { name: "Chad", code: "TD" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN" },
  { name: "Colombia", code: "CO" },
  { name: "Comoros", code: "KM" },
  { name: "Congo (Congo-Brazzaville)", code: "CG" },
  { name: "Costa Rica", code: "CR" },
  { name: "Croatia", code: "HR" },
  { name: "Cuba", code: "CU" },
  { name: "Cyprus", code: "CY" },
  { name: "Czechia (Czech Republic)", code: "CZ" },
  { name: "Denmark", code: "DK" },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "Dominican Republic", code: "DO" },
  { name: "Ecuador", code: "EC" },
  { name: "Egypt", code: "EG" },
  { name: "El Salvador", code: "SV" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Eritrea", code: "ER" },
  { name: "Estonia", code: "EE" },
  { name: "Eswatini (fmr. Swaziland)", code: "SZ" },
  { name: "Ethiopia", code: "ET" },
  { name: "Fiji", code: "FJ" },
  { name: "Finland", code: "FI" },
  { name: "France", code: "FR" },
  { name: "Gabon", code: "GA" },
  { name: "Gambia", code: "GM" },
  { name: "Georgia", code: "GE" },
  { name: "Germany", code: "DE" },
  { name: "Ghana", code: "GH" },
  { name: "Greece", code: "GR" },
  { name: "Grenada", code: "GD" },
  { name: "Guatemala", code: "GT" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Guyana", code: "GY" },
  { name: "Haiti", code: "HT" },
  { name: "Honduras", code: "HN" },
  { name: "Hungary", code: "HU" },
  { name: "Iceland", code: "IS" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE" },
  { name: "Israel", code: "IL" },
  { name: "Italy", code: "IT" },
  { name: "Jamaica", code: "JM" },
  { name: "Japan", code: "JP" },
  { name: "Jordan", code: "JO" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kiribati", code: "KI" },
  { name: "Kuwait", code: "KW" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: "Laos", code: "LA" },
  { name: "Latvia", code: "LV" },
  { name: "Lebanon", code: "LB" },
  { name: "Lesotho", code: "LS" },
  { name: "Liberia", code: "LR" },
  { name: "Libya", code: "LY" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malaysia", code: "MY" },
  { name: "Maldives", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Marshall Islands", code: "MH" },
  { name: "Mauritania", code: "MR" },
  { name: "Mauritius", code: "MU" },
  { name: "Mexico", code: "MX" },
  { name: "Micronesia", code: "FM" },
  { name: "Moldova", code: "MD" },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN" },
  { name: "Montenegro", code: "ME" },
  { name: "Morocco", code: "MA" },
  { name: "Mozambique", code: "MZ" },
  { name: "Myanmar (formerly Burma)", code: "MM" },
  { name: "Namibia", code: "NA" },
  { name: "Nauru", code: "NR" },
  { name: "Nepal", code: "NP" },
  { name: "Netherlands", code: "NL" },
  { name: "New Zealand", code: "NZ" },
  { name: "Nicaragua", code: "NI" },
  { name: "Niger", code: "NE" },
  { name: "Nigeria", code: "NG" },
  { name: "North Korea", code: "KP" },
  { name: "North Macedonia", code: "MK" },
  { name: "Norway", code: "NO" },
  { name: "Oman", code: "OM" },
  { name: "Pakistan", code: "PK" },
  { name: "Palau", code: "PW" },
  { name: "Palestine State", code: "PS" },
  { name: "Panama", code: "PA" },
  { name: "Papua New Guinea", code: "PG" },
  { name: "Paraguay", code: "PY" },
  { name: "Peru", code: "PE" },
  { name: "Philippines", code: "PH" },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Qatar", code: "QA" },
  { name: "Romania", code: "RO" },
  { name: "Russia", code: "RU" },
  { name: "Rwanda", code: "RW" },
  { name: "Saint Kitts and Nevis", code: "KN" },
  { name: "Saint Lucia", code: "LC" },
  { name: "Saint Vincent and the Grenadines", code: "VC" },
  { name: "Samoa", code: "WS" },
  { name: "San Marino", code: "SM" },
  { name: "Sao Tome and Principe", code: "ST" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia", code: "RS" },
  { name: "Seychelles", code: "SC" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Singapore", code: "SG" },
  { name: "Slovakia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "Solomon Islands", code: "SB" },
  { name: "Somalia", code: "SO" },
  { name: "South Africa", code: "ZA" },
  { name: "South Korea", code: "KR" },
  { name: "South Sudan", code: "SS" },
  { name: "Spain", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sudan", code: "SD" },
  { name: "Suriname", code: "SR" },
  { name: "Sweden", code: "SE" },
  { name: "Switzerland", code: "CH" },
  { name: "Syria", code: "SY" },
  { name: "Tajikistan", code: "TJ" },
  { name: "Tanzania", code: "TZ" },
  { name: "Thailand", code: "TH" },
  { name: "Timor-Leste", code: "TL" },
  { name: "Togo", code: "TG" },
  { name: "Tonga", code: "TO" },
  { name: "Trinidad and Tobago", code: "TT" },
  { name: "Tunisia", code: "TN" },
  { name: "Turkey", code: "TR" },
  { name: "Turkmenistan", code: "TM" },
  { name: "Tuvalu", code: "TV" },
  { name: "Uganda", code: "UG" },
  { name: "Ukraine", code: "UA" },
  { name: "United Arab Emirates", code: "AE" },
  { name: "United Kingdom", code: "GB" },
  { name: "United States", code: "US" },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Vanuatu", code: "VU" },
  { name: "Vatican City", code: "VA" },
  { name: "Venezuela", code: "VE" },
  { name: "Vietnam", code: "VN" },
  { name: "Yemen", code: "YE" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
];

export const COUNTRYCODE = [
  { country: "United States", shortCode: "US", countryCode: "+1" },
  { country: "Canada", shortCode: "CA", countryCode: "+1" },
  { country: "United Kingdom", shortCode: "GB", countryCode: "+44" },
  { country: "Australia", shortCode: "AU", countryCode: "+61" },
  { country: "India", shortCode: "IN", countryCode: "+91" },
  { country: "Germany", shortCode: "DE", countryCode: "+49" },
  { country: "France", shortCode: "FR", countryCode: "+33" },
  { country: "China", shortCode: "CN", countryCode: "+86" },
  { country: "Japan", shortCode: "JP", countryCode: "+81" },
  { country: "Brazil", shortCode: "BR", countryCode: "+55" },
  { country: "Russia", shortCode: "RU", countryCode: "+7" },
  { country: "South Africa", shortCode: "ZA", countryCode: "+27" },
  { country: "Italy", shortCode: "IT", countryCode: "+39" },
  { country: "Mexico", shortCode: "MX", countryCode: "+52" },
  { country: "Netherlands", shortCode: "NL", countryCode: "+31" },
  { country: "Spain", shortCode: "ES", countryCode: "+34" },
  { country: "Switzerland", shortCode: "CH", countryCode: "+41" },
  { country: "Turkey", shortCode: "TR", countryCode: "+90" },
  { country: "United Arab Emirates", shortCode: "AE", countryCode: "+971" },
  { country: "Saudi Arabia", shortCode: "SA", countryCode: "+966" },
  { country: "New Zealand", shortCode: "NZ", countryCode: "+64" },
  { country: "Singapore", shortCode: "SG", countryCode: "+65" },
  { country: "South Korea", shortCode: "KR", countryCode: "+82" },
  { country: "Indonesia", shortCode: "ID", countryCode: "+62" },
  { country: "Malaysia", shortCode: "MY", countryCode: "+60" },
];
