export const CURRENCIES = [
  {
    currencyCode: "USD",
    currencyName: "US Dollar",
    countries: [
      "United States",
      "American Samoa",
      "British Indian Ocean Territory",
      "Ecuador",
      "El Salvador",
      "Guam",
      "Haiti",
      "Marshall Islands",
      "Micronesia",
      "Northern Mariana Islands",
      "Palau",
      "Panama",
      "Puerto Rico",
      "Timor-Leste",
      "Turks and Caicos Islands",
      "U.S. Virgin Islands",
    ],
  },
  {
    currencyCode: "EUR",
    currencyName: "Euro",
    countries: [
      "Austria",
      "Belgium",
      "Cyprus",
      "Estonia",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Ireland",
      "Italy",
      "Latvia",
      "Lithuania",
      "Luxembourg",
      "Malta",
      "Netherlands",
      "Portugal",
      "Slovakia",
      "Slovenia",
      "Spain",
    ],
  },
  {
    currencyCode: "JPY",
    currencyName: "Japanese Yen",
    countries: ["Japan"],
  },
  {
    currencyCode: "GBP",
    currencyName: "Pound Sterling",
    countries: [
      "United Kingdom",
      "South Georgia and the South Sandwich Islands",
    ],
  },
  {
    currencyCode: "AUD",
    currencyName: "Australian Dollar",
    countries: [
      "Australia",
      "Christmas Island",
      "Cocos (Keeling) Islands",
      "Heard Island and McDonald Islands",
      "Kiribati",
      "Nauru",
      "Norfolk Island",
      "Tuvalu",
    ],
  },
  {
    currencyCode: "CAD",
    currencyName: "Canadian Dollar",
    countries: ["Canada"],
  },
  {
    currencyCode: "CHF",
    currencyName: "Swiss Franc",
    countries: ["Switzerland", "Liechtenstein"],
  },
  {
    currencyCode: "CNY",
    currencyName: "Chinese Yuan",
    countries: ["China"],
  },
  {
    currencyCode: "SEK",
    currencyName: "Swedish Krona",
    countries: ["Sweden"],
  },
  {
    currencyCode: "NZD",
    currencyName: "New Zealand Dollar",
    countries: ["New Zealand", "Cook Islands", "Niue", "Pitcairn", "Tokelau"],
  },
  {
    currencyCode: "KRW",
    currencyName: "South Korean Won",
    countries: ["South Korea"],
  },
  {
    currencyCode: "SGD",
    currencyName: "Singapore Dollar",
    countries: ["Singapore"],
  },
  {
    currencyCode: "HKD",
    currencyName: "Hong Kong Dollar",
    countries: ["Hong Kong"],
  },
  {
    currencyCode: "NOK",
    currencyName: "Norwegian Krone",
    countries: ["Norway", "Bouvet Island"],
  },
  {
    currencyCode: "MXN",
    currencyName: "Mexican Peso",
    countries: ["Mexico"],
  },
  {
    currencyCode: "INR",
    currencyName: "Indian Rupee",
    countries: ["India"],
  },
  {
    currencyCode: "RUB",
    currencyName: "Russian Ruble",
    countries: ["Russia"],
  },
  {
    currencyCode: "ZAR",
    currencyName: "South African Rand",
    countries: ["South Africa"],
  },
  {
    currencyCode: "TRY",
    currencyName: "Turkish Lira",
    countries: ["Turkey"],
  },
  {
    currencyCode: "BRL",
    currencyName: "Brazilian Real",
    countries: ["Brazil"],
  },
];
