import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans } from "next/font/google";
import "./globals.scss";
import InnerLayout from "../../components/Layout/InnerLayout";
import syncDatabase from "../lib/sync";
import AuthProvider from "../../components/auth-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const notoSans = Noto_Sans({
  subsets: ['latin'], // You can specify subsets like 'latin', 'cyrillic', etc.
  weight: ['400','500','600', '700'], // Specify font weights if needed
  variable: '--font-noto-sans', // Add a CSS variable for easy use
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await syncDatabase();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}  ${notoSans.variable}`}>
        <AuthProvider>
          <InnerLayout>{children}</InnerLayout>
        </AuthProvider>
      </body>
    </html>
  );
}
